### ISSUE TITLE
Don't add YAML extension to JSON cassettes

### ISSUE THREAD

**Issue by dmfigol** [kiwicom/pytest-recording#10]
Thank you for the plugin. Unfortunately, it is really hard to find it as `pytest-vcr` always comes first in the search.

I have the following issue:
If I use `serializer="json"` and I use something like `@pytest.mark.vcr('list_rooms.json')`, then the plugin adds `yaml` extension to the cassette (`list_rooms.json.yaml`), though it is saved as `json` correctly.

**Comment by Stranger6667** [comment]
Hello @dmfigol :) 
Thank you for reporting the issue :) I will take a look tomorrow

**Comment by Stranger6667** [comment]
Fixed in `0.3.2` release (already on PyPI). Feel free to reopen the issue if the problem occurs again :)
