### ISSUE TITLE
Cannot record when use GitPython

### ISSUE THREAD

**Issue by thewalldao** [kiwicom/pytest-recording#117]
Hi guys,
Now I have a testcase use GitPython and take so much time, I want to use pytest-recording to record git request (GitPython), but It cannot record it, Is there anyone who know how to record git request by using GitPython library?

**Comment by Stranger6667** [comment]
Hi! This is more of a question for the underlying vcrpy library - it uses mocks for popular network libraries in order to record traffic. Apparently they don’t have a mock for GitPython underlying machinery

**Comment by thewalldao** [comment]
> Hi! This is more of a question for the underlying vcrpy library - it uses mocks for popular network libraries in order to record traffic. Apparently they don’t have a mock for GitPython underlying machinery

Thank you,
So now I will continue with another solution.
