### ISSUE TITLE
[BUG] vcr.py does not lock down it's dependencies

### ISSUE THREAD

**Issue by LewisCowlesMotive** [kiwicom/pytest-recording#147]
**Describe the bug**

A Dependency of this library (VCR.py) does not lock down it's dependencies
Because of this, and reliance on setuptools deprecated functionality; builds using poetry are now failing.

**To Reproduce**

pip install setuptools=="72.0.0"
pip wheel --no-cache-dir --use-pep517 "vcrpy (==6.0.1)"

**Expected behavior**
VCRPY to install like it did last week

**Environment (please complete the following information):**

- OS: Linux
- Python version: 3.11.9
- pytest-recording version: 0.13.2
- pytest version: N/A
- 
**Additional context**

This is due to the non-fixed approach to transitive dependencies that vcr.py has.

**Comment by Lewiscowles1986** [comment]
setuptools fixed this and yanked a version. Still feels to me that this is all hanging together by luck; but closing.
