### ISSUE TITLE
nitpicking about license

### ISSUE THREAD

**Issue by asmodehn** [kiwicom/pytest-recording#18]
I am totally nitpicking here, but the license is not recognized by https://pyup.io. Some other dependencies I have that are also MIT are recognized...

**Comment by Stranger6667** [comment]
Hello :) it is caused by missing "license" keyword arg in `setup.py`. Now it is updated and the next uploaded package should have the license recognized.

I'll probably add some small feature from our issues list and release a new version soon :)

**Comment by asmodehn** [comment]
Great, thanks !
