### ISSUE TITLE
Use default mode `once` in README

### ISSUE THREAD

**Issue by northtree** [kiwicom/pytest-recording#38]
I'm new to `VCR.py` and `pytest-recording`. Just setup for my scraper project today. 

Followed by the `README` doc, I used `--record-mode=all` to run `pytest`. However, the tests will failed in CI (I used CircleCI) and the YAMLs under cassettes will be changed. 

After read [VCR.py doc](https://vcrpy.readthedocs.io/en/latest/usage.html#once), I change to `--record-mode=once`. Now all the cassettes won't be updated and all tests passed in CI.

IMO, I suggest to use `--record-mode=once` in README, which may be easier for beginner.

**Comment by Stranger6667** [comment]
Hello @northtree !

It is a very good point, thank you for bringing it up :) Changed in 991ba71
