### ISSUE TITLE
How to setup common VCR config for all tests

### ISSUE THREAD

**Issue by northtree** [kiwicom/pytest-recording#39]
The following config seems not working under `tests/__init__.py`, but works within `tests/test_foo.py`, `tests/test_bar.py`...

```python
import pytest


@pytest.fixture(scope='module', autouse=True)
def vcr_config():
  return {'ignore_hosts': ['oauth2.googleapis.com']}
```

**Comment by Stranger6667** [comment]
It should be in `conftest.py`, `pytest` collects fixtures from `conftest.py` files (in most common cases)

**Comment by Stranger6667** [comment]
Hopefully, the problem is resolved now. We can add some clarification to our `Configuration` section as a part of #49.

Feel free to reopen this issue in case of any further questions
