### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by nomasprime** [kiwicom/pytest-recording#49]
Readme doesn't document requirements, setup process, etc.

I've installed pytest-recording and hacking around now to get it working but would be great if this was all part of the Readme.

**Comment by nomasprime** [comment]
Of course as soon as I raised this I discovered that cassettes are being recorded just in a location I didn't expect 😄

**Comment by Stranger6667** [comment]
Hi!
Thank you for bringing this topic! It is definitely something we can improve :) What do you think if we'll add some kind of quickstart guide that will include all steps from an existing project without VCR / pytest-recording to fully working test suite + document how cassettes are recorded? Are there any particular points (besides those you mentioned in the first message) you think we need to address first?

**Comment by nomasprime** [comment]
Hey @Stranger6667, that's a great idea.

I'm new to Python and think it was mostly me not realising a couple of fairly obvious things but your suggestion probably would reduce the friction to virtually nothing 👍

**Comment by Stranger6667** [comment]
Would you mind reviewing it once I'll have a prototype? Not sure when I'll have time to get into this, but probably this week

**Comment by nomasprime** [comment]
Thanks @Stranger6667. Of course, happy to help anyway I can.

**Comment by Stranger6667** [comment]
Implementation notes for anyone willing to contribute (or for myself, when I'll get back to it):
- Add the "Installation" section before "Usage";
- Add installation instructions like `pip install pytest-recording`;
- Mention that this plugin is not compatible with `pytest-vcr` and you need to uninstall `pytest-vcr` to use `pytest-recording`;
- In the readme, add a link to the VCR-py repo where appropriate;
- In the "Usage" section, add a short description of the usual workflow - add marks, run tests with `--record-mode=all`, see cassettes created, then rerun tests, and no network is used.
