### ISSUE TITLE
What is the relationship to pytest-vcr?

### ISSUE THREAD

**Issue by MartinThoma** [kiwicom/pytest-recording#52]
I have seen [pytest-recording](https://github.com/ktosiek/pytest-vcr) (on [pypi](https://pypi.org/project/pytest-recording/)) which looks pretty similar:

* Uses `@pytest.mark.vcr` 
* Both seem to be wrappers around vcr.py
* 49 stars, 3 forks, 2 contributors vs 67 stars, 17 forks, 7 contributors
* First tag in 2019 vs first tag in 2017

My guess is that `pytest-recording` is a fork of `pytest-vcr`. But why was the fork done and what is the relationship to pytest-vcr? When should one use one or the other?

**Comment by Stranger6667** [comment]
Hello @MartinThoma 

Thank you for asking! It is not a fork, but implementation from scratch. I had a slightly different vision of plugin's API and features. We used `pytest-vcr` before and [submitted](https://github.com/ktosiek/pytest-vcr/pull/25) a PR to adjust the API. However, it wasn't addressed by the `pytest-vcr` author and some other PRs were not addressed either - to me, the library looked abandoned.
There is [more info](https://github.com/kevin1024/vcrpy/issues/476#issue-482015637) about the differences between these two plugins, but there are some new changes that were not yet done when I wrote that comment in the link above:
- `pytest-recording` is not affected by [this](https://github.com/ktosiek/pytest-vcr/pull/24) bug reported to `pytest-vcr`
- it provides `pytest_recording_configure` hook for better customization
- `rewrite` record mode, that was actually [requested](https://github.com/kevin1024/vcrpy/issues/208) in `VCRpy` itself
- Pytest assertions rewriting for better error output ([wasn't](https://github.com/ktosiek/pytest-vcr/pull/28) addressed in `pytest-vcr`)

> When should one use one or the other?

I'd say that there are more features in `pytest-recording`, than in `pytest-vcr` and one of my explicit goals was to have a drop-in replacement for `pytest-vcr`, but I am biased and might miss something in `pytest-vcr`. However, I'd be happy to know if anything is missing and implement it here :)

Let me know if I can provide more info to you

**Comment by MartinThoma** [comment]
Thank you very much! This helps a lot :-)
