### ISSUE TITLE
[FEATURE] Run Python 3.9 builds

### ISSUE THREAD

**Issue by Stranger6667** [kiwicom/pytest-recording#61]
- Add `39` to `envlist` in `tox.ini`
- Add `39` to `depends` of the `coverage-report` job in `tox.ini`
- Add `Programming Language :: Python :: 3.9` to the classifiers list in `setup.py`
- Add Python 3.9 job in `.github/workflows/build.yml` similarly to other builds

**Comment by pengincoalition** [comment]
Can I work on this issue.

**Comment by Stranger6667** [comment]
Sure!
