### ISSUE TITLE
Flag to turn on/off vcr

### ISSUE THREAD

**Issue by MasterSergius** [kiwicom/pytest-recording#64]
Hi, 
I'd like to have some flag (the best option env variable), to turn on/off vcr for tests marked with `@pytest.mark.vcr`.
By default it should work as is. But if I set env variable "USE_VCR=false" it should run real http requests and no cassetes should be rewritten. Or it is possible to achieve somehow with CLI options, custom decorators, etc?

**Comment by MasterSergius** [comment]
I'd like to make small update (until better solution is introduced): it's possible to override vcr fixture, thus I can turn it on/off in overridden fixture in many different ways.

**Comment by Stranger6667** [comment]
Hi there!

Thank you for asking! Unfortunately, I didn't have much time to respond, but I will get back to you tomorrow :)

**Comment by Stranger6667** [comment]
> Or it is possible to achieve somehow with CLI options, custom decorators, etc?

> I'd like to make small update (until better solution is introduced): it's possible to override vcr fixture, thus I can turn it on/off in overridden fixture in many different ways.

Yep, it is currently possible with overriding existing fixtures. #65 introduces the ``--disable-recording`` CLI option that completely disables the VCR.py integration, but I am not yet sure about adding an env variable - maybe env variables can be introduced later.

**Comment by Stranger6667** [comment]
This feature is released in [0.11.0](https://pypi.org/project/pytest-recording/0.11.0/)

**Comment by MasterSergius** [comment]
Thank you for quick action :)

**Comment by Stranger6667** [comment]
You're very welcome! :)
