### ISSUE TITLE
Is there a no decorator mode?

### ISSUE THREAD

**Issue by ubalklen** [kiwicom/pytest-recording#86]
I have many tests and I want almost all of them to be recorded. Is there a way to record all of them by default without the need of adding a decorator to each one?

**Comment by Stranger6667** [comment]
you could use a module-level `pytestmark` or use hooks to mark tests dynamically.

```python
# in your test file
pytestmark = [pytest.mark.vcr]
```

See more in Pytest [docs](https://docs.pytest.org/en/7.1.x/example/markers.html#marking-whole-classes-or-modules)

**Comment by ubalklen** [comment]
That will do. Thanks!
