### ISSUE TITLE
Filter sensitive data from response/how to use `before_record_response`?

### ISSUE THREAD

**Issue by ghost** [kiwicom/pytest-recording#94]
One of my cassettes makes a call to an authorization endpoint and therefore has sensitive data (`access_token`, etc) in the response body. Is there a way to filter the sensitive data from the response body, similar to the `before_record_response` function in vcr.py? I tried calling that function from my code but it didn't work: `@pytest.mark.vcr(before_record_response=lambda r: None)`.

**Comment by psdon** [comment]
Use vcr_config
```python
@pytest.fixture(scope="module")
def vcr_config():
    return {
        "filter_headers": [
            "Authorization"
        ]
    }
```

**Comment by Stranger6667** [comment]
Indeed, the `vcr_config` fixture should be used for this purpose
